# Generated by Django 3.0.4 on 2020-04-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20200420_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadpdf',
            name='resumes',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
