# Generated by Django 3.0.4 on 2020-04-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20200420_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadpdf',
            name='jobrole',
        ),
    ]
