# Generated by Django 3.0.4 on 2020-04-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_auto_20200427_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadkeyword',
            name='keyword',
            field=models.FileField(blank=True, null=True, upload_to='keyword/'),
        ),
    ]
